# Generated by Django 3.0.6 on 2020-05-31 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200531_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='videofile',
        ),
    ]
