# Generated by Django 3.0.6 on 2020-06-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200601_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
    ]
