# Generated by Django 3.0.6 on 2020-06-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200602_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.TextField(max_length=1160, null=True),
        ),
    ]
