# Generated by Django 3.0.6 on 2020-06-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
